<?php

/**
 * @file hosting_queued.module
 * Contains hooks for the queue daemon module.
 */

/**
 * Implements hook_menu().
 */
function hosting_queued_menu() {
  $items['admin/hosting/queued'] = array(
    'title' => 'Queue daemon',
    'description' => 'Configure the daemonized tasks queue daemon.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_queued_settings_form'),
    'access arguments' => array('administer hosting queues'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'hosting_queued.admin.inc',
  );
  $items['admin/hosting/queued/semaphore'] = array(
    'title' => 'Unlock Hosting Queue',
    'description' => 'Remove the semaphore lock.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_queued_remove_semaphore_form'),
    'access arguments' => array('administer hosting queues'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'hosting_queued.admin.inc',
  );
  return $items;
}
